Add a test for the stable/policy-limitmemory policy
stolostron/governance-policy-framework pull request #296
Opened 2022-03-18 17:42 UTC by mprahl

Resolves:
https://github.com/stolostron/backlog/issues/20844

2022-03-18 17:42 UTC, mprahl commented
/hold for merge strategy

2022-03-18 18:10 UTC, dhaiducek submitted a review, later dismissed
/hold (in case you want to dismiss the nits 😉 )

Looks good to me!

Nit: Should the name of the file match the name of the policy and file? (i.e. `policy-limitmemory_test.go`?)

2022-03-18 18:18 UTC, mprahl commented
Thanks for the review @dhaiducek! The nits are picked.  :smile:

I imagine I'll have to rebase again shortly after #295 is merged.

2022-03-18 19:20 UTC, dhaiducek approved these changes

2022-03-18 20:50 UTC, ycao56 commented on test/integration/policy-limitmemory_test.go
> +var limitMemoryLabel = Label("policy-collection", "stable", "BVT")
Looks good. The only thing is I would suggest not to put BVT label on it. The config policy controller has been already tested by other test cases. It's safe to leave this test case for SVT.

2022-03-18 23:13 UTC, ycao56 requested changes

2022-03-18 23:13 UTC, ycao56 commented on test/integration/policy-limitmemory_test.go
> +				_, err := clientHub.CoreV1().LimitRanges(userNamespace).Get(
```suggestion
				_, err := clientManaged.CoreV1().LimitRanges(userNamespace).Get(
```

2022-03-18 23:13 UTC, ycao56 commented on test/integration/policy-limitmemory_test.go
> +		err = clientHub.CoreV1().LimitRanges(userNamespace).Delete(
```suggestion
		err = clientManaged.CoreV1().LimitRanges(userNamespace).Delete(
```

2022-03-21 12:21 UTC, mprahl commented on test/integration/policy-limitmemory_test.go
> +				_, err := clientHub.CoreV1().LimitRanges(userNamespace).Get(
Thanks for catching that!

2022-03-21 12:22 UTC, ycao56 approved these changes

2022-03-21 15:23 UTC, merged