Address cleanup concern when kyverno tests fail
stolostron/governance-policy-framework pull request #388
Opened 2022-06-08 17:00 UTC by gparvin

Cleanup can be a concern when the tests are run on a long running
cluster.  This change makes sure cleanup is called.

Refs:
 - https://github.com/stolostron/backlog/issues/22938

Signed-off-by: Gus Parvin <gparvin@redhat.com>

2022-06-08 17:00 UTC, gparvin commented
/hold

2022-06-08 17:15 UTC, dhaiducek requested changes

2022-06-08 17:15 UTC, dhaiducek commented on test/integration/policy_kyverno_generators_test.go
> +	Describe("Test stable kyverno generator policies", Ordered, func() {
I think this `Describe` can be removed and the `Ordered` added to its parent. I'm not sure a nested Describe is necessary here.

2022-06-09 15:44 UTC, JustinKuli submitted a review, later dismissed
/retest

Looks good! I think this will help prevent the situation our e2e cluster is currently in :D

2022-06-09 16:47 UTC, JustinKuli commented
/retest

2022-06-14 19:41 UTC, gparvin commented
/retest

2022-06-14 20:15 UTC, gparvin commented
hibernation failures
/retest

2022-06-14 20:29 UTC, gparvin commented
/retest
Maybe it will get a new cluster...

2022-06-15 13:39 UTC, gparvin commented
/retest

2022-06-23 13:29 UTC, dhaiducek approved these changes

2022-06-23 13:54 UTC, JustinKuli commented
/unhold

2022-06-23 15:30 UTC, gparvin commented
Looks like an unrelated error in limitrange test.
/retest

2022-06-23 16:38 UTC, merged