Change the adding cert secret from command to policy
stolostron/governance-policy-framework pull request #782
Opened 2024-04-09 21:24 UTC by yiraeChristineKim

This will fix https://redhat-internal.slack.com/archives/CVAB9H3DE/p1712678150872979 issue

2024-04-10 13:33 UTC, yiraeChristineKim commented
/test test-e2e-grc-framework

2024-04-10 17:22 UTC, yiraeChristineKim commented
/test test-e2e-grc-framework

2024-04-10 17:23 UTC, yiraeChristineKim commented
/retest test-e2e-grc-framework

2024-04-10 17:29 UTC, yiraeChristineKim commented
/test test-e2e-grc-framework

2024-04-10 18:51 UTC, dhaiducek commented
Found it: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stolostron_governance-policy-framework/782/pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework/1778053794530070528

```
Ran 176 of 182 Specs in 1744.791 seconds
SUCCESS! -- 176 Passed | 0 Failed | 0 Pending | 6 Skipped
PASS
```

2024-04-10 19:01 UTC, dhaiducek requested changes

2024-04-11 16:37 UTC, yiraeChristineKim commented
/test test-e2e-grc-framework

2024-04-11 16:39 UTC, yiraeChristineKim commented on test/integration/compliance_history_test.go
> +				By("Verifying cluster: " + cluster)
Let's remove this. I don't think this is necessary

2024-04-11 19:00 UTC, mprahl submitted a review, later dismissed

2024-04-12 13:50 UTC, mprahl approved these changes

2024-04-12 14:26 UTC, yiraeChristineKim commented
/test test-e2e-grc-framework

2024-04-12 15:50 UTC, merged

2024-04-12 18:57 UTC, yiraeChristineKim commented
/cherry-pick release-2.10